export const Endpoints = {
  dashboard: '',
  orders: 'orders',
  chats: 'chats',
  clients: 'clients',
  products: 'products',
  favorites: 'favorites',
  cart: 'cart',
  variants: 'variants',
  login: 'login',
  users: 'users',
  register: 'register',
  create: 'create',
  update: 'update',
  profile: 'profile',
} as const;
